# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Text-NASA_Ames
version:      0.03
version_from: lib/Text/NASA_Ames.pm
installdirs:  site
requires:
    Class::Accessor:               0.1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
